# SELECT
#     PARENT_ID,
#     COUNT(*) AS COUNT_CHILD
# FROM
#     ECOLI_DATA
# GROUP BY PARENT_ID

SELECT
    A.ID,
    CASE 
        WHEN ISNULL(B.COUNT_CHILD) THEN 0
        ELSE B.COUNT_CHILD
    END AS CHILD_COUNT
    
FROM
    ECOLI_DATA AS A LEFT JOIN
    (SELECT
    PARENT_ID,
    COUNT(*) AS COUNT_CHILD
FROM
    ECOLI_DATA
GROUP BY PARENT_ID) AS B ON A.ID = B.PARENT_ID
ORDER BY
    ID ASC