# select date_format(SALES_DATE,"%Y-%m-%d") as SALES_DATE,PRODUCT_ID, USER_ID, SALES_AMOUNT from ONLINE_SALE 
# where SALES_DATE Between "2022-03-01" and "2022-03-31"
# union all

# select date_format(SALES_DATE,"%Y-%m-%d") as SALES_DATE,PRODUCT_ID, NULL USER_ID, SALES_AMOUNT from OFFLINE_SALE 
# where SALES_DATE Between "2022-03-01" and "2022-03-31"
# order by SALES_DATE,PRODUCT_ID,USER_ID
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    ONLINE_SALE
WHERE
    SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION

SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID,
    NULL USER_ID,
    SALES_AMOUNT
FROM
    OFFLINE_SALE
WHERE
    SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY
    SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC