SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
LEFT JOIN ( 
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
) AS RENTAL_CONFLICT
ON C.CAR_ID = RENTAL_CONFLICT.CAR_ID
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND RENTAL_CONFLICT.CAR_ID IS NULL
HAVING
    FEE >= 500000 AND FEE < 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;