SELECT
    ID,
    CASE 
        WHEN NTILE_GROUP = 1 THEN 'CRITICAL'
        WHEN NTILE_GROUP = 2 THEN 'HIGH'
        WHEN NTILE_GROUP = 3 THEN 'MEDIUM'
        WHEN NTILE_GROUP = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM
    (
        SELECT
            ID,
            NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NTILE_GROUP
        FROM
            ECOLI_DATA
    ) AS NEW_TABLE
ORDER BY
    ID ASC