WITH USER_2021 AS (
    SELECT
        COUNT(USER_ID) AS TOTAL_2021_USERS
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = 2021
),
PURCHASED_2021_USERS AS (
    SELECT DISTINCT
        YEAR(OS.SALES_DATE) AS SALES_YEAR,
        MONTH(OS.SALES_DATE) AS SALES_MONTH,
        OS.USER_ID
    FROM
        ONLINE_SALE AS OS
    JOIN
        USER_INFO AS UI ON OS.USER_ID = UI.USER_ID
    WHERE
        YEAR(UI.JOINED) = 2021 -- 2021년에 가입한 회원만
)
SELECT
    P.SALES_YEAR AS YEAR,
    P.SALES_MONTH AS MONTH,
    COUNT(P.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(P.USER_ID) / (SELECT TOTAL_2021_USERS FROM USER_2021), 1) AS PUCHASED_RATIO 
FROM
    PURCHASED_2021_USERS AS P
GROUP BY
    P.SALES_YEAR,
    P.SALES_MONTH
ORDER BY
    YEAR ASC,
    MONTH ASC;