-- 코드를 입력하세요
SELECT
    FD.PRODUCT_ID,
    FD.PRODUCT_NAME,
    SUM(OD.AMOUNT) * FD.PRICE AS TOTAL_SALES
    
FROM
    FOOD_PRODUCT AS FD
JOIN 
    FOOD_ORDER AS OD ON FD.PRODUCT_ID = OD.PRODUCT_ID
WHERE
    YEAR(OD.PRODUCE_DATE) = 2022 AND MONTH(OD.PRODUCE_DATE) = 5
GROUP BY
    OD.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, FD.PRODUCT_ID ASC;