SELECT
    B.APNT_NO,
    A.PT_NAME,
    B.PT_NO,
    B.MCDP_CD,
    C.DR_NAME,
    B.APNT_YMD
FROM
    PATIENT AS A
JOIN
    APPOINTMENT AS B ON A.PT_NO = B.PT_NO
JOIN
    DOCTOR AS C ON B.MDDR_ID = C.DR_ID
WHERE
    DATE_FORMAT(B.APNT_YMD, "%Y-%m-%d") = '2022-04-13' AND ISNULL(B.APNT_CNCL_YMD) AND B.MCDP_CD = 'CS'
ORDER BY
    APNT_YMD ASC;

# APNT_CNCL_YMD NULL이면 예약취소가 아님