WITH RECURSIVE HOURS (HOUR) AS (
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT
    H.HOUR,
    COUNT(AN.ANIMAL_ID) AS COUNT
FROM
    HOURS H
LEFT JOIN
    ANIMAL_OUTS AS AN ON H.HOUR = HOUR(AN.DATETIME)

GROUP BY
    HOUR
ORDER BY
    HOUR