WITH FIND_REVIEW AS(
    SELECT
        COUNT(*) AS CT,
        MEMBER_ID,
        REVIEW_TEXT,
        REVIEW_ID
    FROM
        REST_REVIEW 
    GROUP BY
        MEMBER_ID
    ORDER BY
        CT DESC
)

SELECT
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE AS A
JOIN
    REST_REVIEW AS B ON A.MEMBER_ID = B.MEMBER_ID
JOIN
    FIND_REVIEW AS C ON A.MEMBER_ID = C.MEMBER_ID
WHERE C.CT = (
    SELECT
        MAX(CT)
    FROM
        FIND_REVIEW
    )
ORDER BY
    REVIEW_DATE ASC, REVIEW_TEXT ASC;