WITH SKILL_CODES AS (
    SELECT
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS PYTHON_CODE,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS CSHARP_CODE,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FRONT_END_CODE
),
DEVELOPER_WITH_GRADE AS (
    SELECT
        D.ID,
        D.EMAIL,
        CASE
            WHEN (D.SKILL_CODE & S.PYTHON_CODE) > 0 AND (D.SKILL_CODE & S.FRONT_END_CODE) > 0 THEN 'A'
            WHEN (D.SKILL_CODE & S.CSHARP_CODE) > 0 THEN 'B'
            WHEN (D.SKILL_CODE & S.FRONT_END_CODE) > 0 THEN 'C'
            ELSE NULL
        END AS GRADE
    FROM
        DEVELOPERS D, SKILL_CODES S
)
SELECT
    GRADE,
    ID,
    EMAIL
FROM
    DEVELOPER_WITH_GRADE
WHERE
    GRADE IS NOT NULL
ORDER BY
    GRADE ASC, ID ASC;
